version: '3.0'
services:
  web:
    build: ./web_app
    ports:
    - "8080:3000"
  gateway-db:
    image: postgres
    volumes:
      - gateway-database:/var/lib/postgresql/data
    env_file:
      - gateway/db.env
  gateway:
    build: ./gateway
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./gateway:/app
    ports:
      - "3000:3000"
    depends_on:
      - gateway-db
    env_file:
      - gateway/.env
    stdin_open: true
    tty: true
  storage:
    build: ./storage
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - ./storage:/app
    ports:
      - "5000:5000"
  results_stats:
    build: ./results_stats
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 9000 -b '0.0.0.0'"
    volumes:
      - ./results_stats:/app
    ports:
      - "9000:9000"
    depends_on:
      - results-db
  results-db:
    image: mongo:3
    volumes:
      - results-database:/data/db

volumes:
  gateway-database:
  results-database:
