version: '3.0'
services:
  web:
    build: ./web_app
    ports:
    - "8080:3000"
  gateway-db:
    image: postgres
    volumes:
      - gateway-database:/var/lib/postgresql/data
    env_file:
      - gateway/db.env
  gateway:
    build: ./gateway
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - ./gateway:/app
    ports:
      - "3000:8000"
    depends_on:
      - gateway-db
    env_file:
      - gateway/.env
  results_stats:
    build: ./results_stats
    ports:
      - "8000:8080"
  storage:
    build: ./storage
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - ./storage:/app
    ports:
      - "5000:5000"

volumes:
  gateway-database:
