source 'https://rubygems.org'

gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
gem 'rest-client'
gem 'bcrypt'
gem 'jwt'
gem 'devise'
gem 'devise-jwt'
gem "settingslogic"
gem "pundit"

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'rspec'
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem 'spring'
end

group :test do
  gem 'database_cleaner-active_record'
end
