development:
  clients:
    default:
      database: results_stats_development
      hosts:
        - results-db:27017
      options:
        server_selection_timeout: 1

  options:
    use_utc: true

test:
  clients:
    default:
      database: results_stats_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
