source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors'
gem "lograge"
gem 'image_processing'

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem "pry-rails"
  gem 'rspec'
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem 'spring'
end

group :test do
  gem "shoulda-matchers"
  gem 'database_cleaner-active_record'
end
