default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user:     gateway_user
  password: 123456

development:
  <<: *default
  database: gateway_development
  host:     <%= ENV.fetch("CONTAINER") { false } ? "gateway-db" : "localhost" %>

test:
  <<: *default
  database: gateway_test
  host:     <%= ENV.fetch("CONTAINER") { false } ? "gateway-db" : "localhost" %>

production:
  <<: *default
  database: gateway_production
  username: gateway
  password: <%= ENV['GATEWAY_DATABASE_PASSWORD'] %>
